local hl = require("hl")

-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 27)

hl.env("XCURSOR_THEME", "Catppuccin-Macchiato-Dark")

hl.env("HYPRCURSOR_SIZE", 27)

hl.env("HYPRCURSOR_THEME", "Catppuccin-Macchiato-Dark")

hl.env("BROWSER", "brave-browser")

local browser = "brave-browser"

hl.env("SSH_AUTH_SOCK", "/run/user/1000/keyring/ssh")
