local hl = require("hl")

-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "1",
})

--monitor = eDP-1, 1920x1080@60, 0x0, 1 #for manual adjustment

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60",
    position = "auto",
    scale    = 1,
    mirror = "eDP-1",
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        repeat_delay = 300,
        repeat_rate = 40,
        kb_layout = "us",
        numlock_by_default = false,
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
            disable_while_typing = false,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
    gestures = {
        --workspace_swipe = true
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.1,
})
