local hl = require("hl")

-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- Note: In Hyprland 0.53+, we use 'windowrule' with 'match:' properties.

-- -----------------------------------------------------

-- 1. Global Safety & Floats

-- -----------------------------------------------------

-- Fix: 'suppressevent' -> 'suppress_event', and strictly match all classes

--windowrule = suppress_event maximize, match:class .*

-- Fix: 'float' now usually needs '1' (true) or 'on'

--windowrule = float 1, match:class ^(kitty)$

-- -----------------------------------------------------

-- 2. Authentication Agents (Polkit)

-- -----------------------------------------------------

-- Fix: 'stayfocused' -> 'stay_focused' (snake_case)

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(polkit-gnome-authentication-agent-1)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(polkit-gnome-authentication-agent-1)$",
    },
    center = 1,
})

--windowrule = stay_focused, match:class ^(polkit-gnome-authentication-agent-1)$

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    center = 1,
})

--windowrule = stay_focused, match:class ^(org.kde.polkit-kde-authentication-agent-1)$

-- -----------------------------------------------------

-- 3. File Wizards (Thunar & Portals)

-- -----------------------------------------------------

-- XDG Desktop Portals (GTK/KDE)

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    center = 1,
})

hl.window_rule({
    name  = "size_900_600",
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    size = "900 600",
})

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(xdg-desktop-portal-kde)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(xdg-desktop-portal-kde)$",
    },
    center = 1,
})

hl.window_rule({
    name  = "size_900_600",
    match = {
        class = "^(xdg-desktop-portal-kde)$",
    },
    size = "900 600",
})

-- Thunar "Wizard" Windows

-- Note: We must match BOTH class and title. 

-- New syntax allows multiple matches in one line, but separate lines are safer for debugging.

-- Progress Bar

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(thunar)$",
        title = "^(File Operation Progress)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(thunar)$",
        title = "^(File Operation Progress)$",
    },
    center = 1,
})

-- Confirm Dialog

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(thunar)$",
        title = "^(Confirm to replace files)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(thunar)$",
        title = "^(Confirm to replace files)$",
    },
    center = 1,
})

-- Properties

hl.window_rule({
    name  = "float_1",
    match = {
        class = "^(thunar)$",
        title = "^(.*Properties)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        class = "^(thunar)$",
        title = "^(.*Properties)$",
    },
    center = 1,
})

-- -----------------------------------------------------

-- 4. General Dialog Catch-All

-- -----------------------------------------------------

-- Replaces the deprecated 'windowtype:dialog' with title matching

hl.window_rule({
    name  = "float_1",
    match = {
        title = "^(Open File)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        title = "^(Open File)$",
    },
    center = 1,
})

hl.window_rule({
    name  = "size_900_600",
    match = {
        title = "^(Open File)$",
    },
    size = "900 600",
})

hl.window_rule({
    name  = "float_1",
    match = {
        title = "^(Save As)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        title = "^(Save As)$",
    },
    center = 1,
})

hl.window_rule({
    name  = "size_900_600",
    match = {
        title = "^(Save As)$",
    },
    size = "900 600",
})

hl.window_rule({
    name  = "float_1",
    match = {
        title = "^(Select a File)$",
    },
    -- TODO: review rule: "float 1"
})

hl.window_rule({
    name  = "center_1",
    match = {
        title = "^(Select a File)$",
    },
    center = 1,
})
