### AUTOSTART ###
#################
 
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar -c ~/.config/waybar/config-hyprland.jsonc 
#exec-once = swaync 
exec-once = swaybg -i $HOME/Pictures/Wallpapers/walls-main/unsorted/a_room_with_a_large_window_and_a_piano_keyboard_and_a_large_fire.jpg -m fill
exec-once = mako
#exec-once = swww-daemon
#exec-once = hyprpanel
exec-once = nm-applet
exec-once = copyq 
exec-once = kdeconnect-indicator   
exec-once = hypridle
#exec-once = hyprctl setcursor 27
#exec-once = $HOME/scripts/brave_decode_issue.sh
exec-once = brave-browser
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
#exec-once = walker --gapplication-service
exec-once = rclone mount EComp_Gdrive: ~/EComp_Gdrive --vfs-cache-mode writes --vfs-cache-max-size 2G &
